# Generated by Django 3.1.6 on 2021-02-15 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Loan amount')),
                ('interest_type', models.CharField(choices=[('one-time', 'one-time interest'), ('yearly', 'yearly interest')], max_length=10, verbose_name='interest type')),
                ('interest', models.FloatField(choices=[(0, '0%'), (0.5, '0.5%'), (1, '1%'), (1.5, '1.5%'), (2, '2%'), (2.5, '2.5%'), (3, '3%')], verbose_name='interest')),
                ('duration', models.IntegerField(choices=[(1, '1 year'), (2, '2 years'), (5, '5 years'), (10, '10 years')], verbose_name='duration')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedLoan',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loans.loan')),
                ('contract', models.FileField(upload_to='', verbose_name='contract')),
            ],
            options={
                'verbose_name': 'accepted loan',
                'verbose_name_plural': 'accepted loans',
            },
            bases=('loans.loan',),
        ),
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loans.loan')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='responsible person')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
            },
            bases=('loans.loan',),
        ),
    ]
