# Generated by Django 3.1.6 on 2021-02-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanoffer',
            options={'permissions': [('accept_loanoffer', 'Can upload the contract and accept the offer')], 'verbose_name': 'offer', 'verbose_name_plural': 'offers'},
        ),
        migrations.AlterField(
            model_name='loan',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='contact email'),
        ),
    ]
