# Generated by Django 3.1.6 on 2021-02-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20210220_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanoffer',
            options={'permissions': [('accept_loanoffer', 'Can accept the offer')], 'verbose_name': 'offer', 'verbose_name_plural': 'offers'},
        ),
    ]
