# Generated by Django 3.2.5 on 2021-07-08 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0004_auto_20210220_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='currency',
            field=models.CharField(choices=[('Kč', 'Kč'), ('EUR', 'EUR')], default='Kč', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='acceptedloan',
            name='contract',
            field=models.FileField(upload_to='contracts', verbose_name='contract'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 year'), (2, '2 years'), (3, '3 years'), (4, '4 years'), (5, '5 years'), (6, '6 years'), (7, '7 years'), (8, '8 years'), (9, '9 years'), (10, '10 years'), (11, '11 years'), (12, '12 years'), (13, '13 years'), (14, '14 years'), (15, '15 years')], verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.FloatField(choices=[(0.0, '0.0 %'), (0.5, '0.5 %'), (1.0, '1.0 %'), (1.5, '1.5 %'), (2.0, '2.0 %'), (2.5, '2.5 %'), (3.0, '3.0 %')], verbose_name='interest'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_type',
            field=models.CharField(choices=[('end', 'repayment of both prinicipal and interest at the end'), ('yearly', 'yearly repayment of interest, principal at the end')], max_length=10, verbose_name='interest repayment type'),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='responsible person'),
        ),
    ]
