# Generated by Django 3.2.5 on 2021-07-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20210708_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='lender_language',
            field=models.CharField(choices=[('cs', 'Czech'), ('de', 'German'), ('en', 'English')], default='cs', max_length=2, verbose_name='lender language'),
        ),
    ]
